version: '3.8'
services:
  mysql-dev:
    image: mysql:8.0
    container_name: uxia-server
    environment:
      MYSQL_DATABASE: uxia
      MYSQL_USER: uxia
      MYSQL_PASSWORD: 978c23h17hfo1
      MYSQL_ROOT_PASSWORD: xl02kfwn1hjhe
    ports:
      - "3306:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    restart: always
volumes:
  mysql-dev-data:
